version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8

    steps:

      - run:
          name: Install dependencies
          command: |
            pip install -r colorama
            pip install pytest

      - run:
          name: Run tests
          command: |
            cd package/tests
            pip install -r requirements.txt
            pytest
